apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: terraform-course
  annotations:
    github.com/project-slug: nagavijjapu/terraform-course
spec:
  type: other
  lifecycle: unknown
  owner: Naga
